openapi: 3.0.3
info:
  title: Swagger Rinha
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: statement
  - name: transaction
paths:
  /clientes/{id}/transacoes:
    post:
      tags:
        - transaction
      summary: Saves a new Transaction for the given client
      description: The Transaction will be saved and the client Statement will be adjusted according to the credit movement
      operationId: saveTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: The new transaction to be saved
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        '200':
          description: Transaction successfully saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
        '404':
          description: Client not found
        '422':
          description: Validation Exception
        '500':
          description: Unexpected Error
  /clientes/{id}/extrato:
    get:
      tags:
        - statement
      summary: Gets the current client statement
      description: Returns the current client balance and its last 10 transactions
      operationId: getStatement
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The client statement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statement'
        '404':
          description: Client not found
        '422':
          description: Validation Exception
        '500':
          description: Unexpected Error
components:
  schemas:
    Transaction:
      type: object
      properties:
        valor:
          type: integer
          format: int64
          description: The transaction value represented in cents
          minimum: 0
          example: 1000
        tipo:
          type: string
          example: c
          enum: [c, d]
          description: The transaction type. 'c' for CREDIT and 'd' for DEBIT
        descricao:
          type: string
          example: descricao
          minLength: 1
          maxLength: 10
    Balance:
      type: object
      properties:
        limite:
          type: integer
          format: int64
          description: The registered client limit
          example: 100000
        saldo:
          type: integer
          format: int64
          description: The new balance value after the transaction
          example: -9098
    Statement:
      type: object
      properties:
        saldo:
          type: object
          properties:
            total:
              type: integer
              description: The current client balance
              example: -9098
            data_extrato:
              type: string
              description: When the statement was fetched
              example: 2024-01-17T02:34:38.543030Z
            limite:
              type: integer
              description: The current client limit
              example: 100000
        ultimas_transacoes:
          type: array
          items:
            $ref: '#/components/schemas/TransactionWithCarriedOut'
    TransactionWithCarriedOut:
      type: object
      properties:
        valor:
          type: integer
          format: int64
          description: The transaction value represented in cents
          minimum: 0
          example: 1000
        tipo:
          type: string
          example: c
          enum: [c, d]
          description: The transaction type. 'c' for CREDIT and 'd' for DEBIT
        descricao:
          type: string
          example: descricao
          minLength: 1
          maxLength: 10
        realizada_em:
          type: string
          description: The date when the transaction carried out
          example: 2024-01-17T02:34:38.543030Z
