version: "3.8"

services:
  db:
    image: postgres:16.2
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    volumes:
      - ./config/postgres-init.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "90MB"

  api01: &api
    image: app-rinha:latest
    restart: no
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "226MB"

  api02:
    <<: *api
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "226MB"

  haproxy:
    image: haproxy:lts-alpine3.19
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "18MB"

  dbAdmin:
    image: dpage/pgadmin4:latest
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"