version: "3.8"

services:
  db:
    image: postgres:16.2
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    volumes:
      - ./config/postgres-init.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  api01: &api
    image: app-rinha:latest
    restart: no
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "230MB"

  api02:
    <<: *api
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "230MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"
